const book_data = [ { title: 'Steal this computer book',
    subtitle: 'what they wont tell you about the internet',
    authors: [ 'Wally Wang' ],
    publisher: 'No Starch Pr',
    publishedDate: '2000-01-15',
    description: 'Explains how computer viruses are created and spread and covers computer harassment, online con artists, encryption, Trojan Horse programs, network security, damage control, and data recovery.',
    industryIdentifiers: [ [Object] ],
    pageCount: 462,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    averageRating: 2,
    ratingsCount: 3,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'pm4EAQAAIAAJ',
    link: 'http://books.google.com/books/about/Steal_this_computer_book.html?hl=&id=pm4EAQAAIAAJ',
    thumbnail: 'http://books.google.com/books/content?id=pm4EAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    images: {} },
  { title: 'Computer Vision',
    subtitle: 'Algorithms and Applications',
    authors: [ 'Richard Szeliski' ],
    publisher: 'Springer Science & Business Media',
    publishedDate: '2010-09-30',
    description: 'Humans perceive the three-dimensional structure of the world with apparent ease. However, despite all of the recent advances in computer vision research, the dream of having a computer interpret an image at the same level as a two-year old remains elusive. Why is computer vision such a challenging problem and what is the current state of the art? Computer Vision: Algorithms and Applications explores the variety of techniques commonly used to analyze and interpret images. It also describes challenging real-world applications where vision is being successfully used, both for specialized applications such as medical imaging, and for fun, consumer-level tasks such as image editing and stitching, which students can apply to their own personal photos and videos. More than just a source of “recipes,” this exceptionally authoritative and comprehensive textbook/reference also takes a scientific approach to basic vision problems, formulating physical models of the imaging process before inverting them to produce descriptions of a scene. These problems are also analyzed using statistical models and solved using rigorous engineering techniques Topics and features: structured to support active curricula and project-oriented courses, with tips in the Introduction for using the book in a variety of customized courses; presents exercises at the end of each chapter with a heavy emphasis on testing algorithms and containing numerous suggestions for small mid-term projects; provides additional material and more detailed mathematical topics in the Appendices, which cover linear algebra, numerical techniques, and Bayesian estimation theory; suggests additional reading at the end of each chapter, including the latest research in each sub-field, in addition to a full Bibliography at the end of the book; supplies supplementary course material for students at the associated website, http://szeliski.org/Book/. Suitable for an upper-level undergraduate or graduate-level course in computer science or engineering, this textbook focuses on basic techniques that work under real-world conditions and encourages students to push their creative boundaries. Its design and exposition also make it eminently suitable as a unique reference to the fundamental techniques and current research literature in computer vision.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 812,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    averageRating: 4,
    ratingsCount: 3,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'bXzAlkODwa8C',
    link: 'https://market.android.com/details?id=book-bXzAlkODwa8C',
    thumbnail: 'http://books.google.com/books/content?id=bXzAlkODwa8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Computer Networks',
    subtitle: 'A Systems Approach',
    authors: [ 'Larry L. Peterson', 'Bruce S. Davie' ],
    publisher: 'Elsevier',
    publishedDate: '2011-03-02',
    description: 'Computer Networks: A Systems Approach, Fifth Edition, discusses the key principles of computer networking. It focuses on the underlying concepts and technologies that make the Internet work. Topics covered include network design and architecture; the ways users can connect to a network; the concepts of switching, routing, and internetworking; end-to-end protocols; congestion control and resource allocation; end-to-end data; network security; and network applications such as e-mail and the Web, IP telephony and video streaming, and peer-to-peer file sharing. Each chapter includes a problem statement, which introduces issues to be examined; shaded sidebars that elaborate on a topic or introduce a related advanced topic; What’s Next? discussions that deal with emerging issues in research, the commercial world, or society; and exercises. This book is written for graduate or upper-division undergraduate classes in computer networking. It will also be useful for industry professionals retraining for network-related assignments, as well as network practitioners seeking to understand the workings of network protocols and the big picture of networking. Completely updated content with expanded coverage of the topics of utmost importance to networking professionals and students, including P2P, wireless, security, and applications Increased focus on application layer issues where innovative and exciting research and design is currently the center of attention Free downloadable network simulation software and lab experiments manual available',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 920,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    averageRating: 3.5,
    ratingsCount: 7,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'BvaFreun1W8C',
    link: 'https://market.android.com/details?id=book-BvaFreun1W8C',
    thumbnail: 'http://books.google.com/books/content?id=BvaFreun1W8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'The Human-Computer Interaction Handbook',
    subtitle: 'Fundamentals, Evolving Technologies and Emerging Applications, Second Edition',
    authors: [ 'Andrew Sears', 'Julie A. Jacko' ],
    publisher: 'CRC Press',
    publishedDate: '2007-09-19',
    description: 'This second edition of The Human-Computer Interaction Handbook provides an updated, comprehensive overview of the most important research in the field, including insights that are directly applicable throughout the process of developing effective interactive information technologies. It features cutting-edge advances to the scientific knowledge base, as well as visionary perspectives and developments that fundamentally transform the way in which researchers and practitioners view the discipline. As the seminal volume of HCI research and practice, The Human-Computer Interaction Handbook features contributions from a selection of eminent professionals in the field worldwide. It stands alone as the most essential resource available on the market. This edition of the volume throughly covers issues of accessibility and diversity, such as aging, literacy, hearing, vision, physical disabilities, and children. Additional topics addressed are: *sensor based interactions; *tangible interfaces; *augmented cognition; *cognition under stress; *ubiquitous and wearable computing; and *privacy and security. This book is useful for practitioners seeking to understand the latest research results to apply when developing new interactive information technologies, as well as for graduate students studying human-centered computing, human-computer interaction, or related fields.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 1384,
    printType: 'BOOK',
    categories: [ 'Technology & Engineering' ],
    averageRating: 3.5,
    ratingsCount: 6,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'A8TPF_O385AC',
    link: 'http://books.google.com/books/about/The_Human_Computer_Interaction_Handbook.html?hl=&id=A8TPF_O385AC',
    thumbnail: 'http://books.google.com/books/content?id=A8TPF_O385AC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Computer Graphics',
    subtitle: 'Theory Into Practice',
    authors: [ 'Jeffrey J. McConnell' ],
    publisher: 'Jones & Bartlett Learning',
    publishedDate: '2006',
    description: 'Computer Graphics & Graphics Applications',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 519,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    averageRating: 2.5,
    ratingsCount: 2,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'H5UVcCYSbXcC',
    link: 'http://books.google.com/books/about/Computer_Graphics.html?hl=&id=H5UVcCYSbXcC',
    thumbnail: 'http://books.google.com/books/content?id=H5UVcCYSbXcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'The Essentials of Computer Organization and Architecture',
    authors:
     [ 'Linda Null',
       'Pennsylvania State University Linda Null',
       'Julia Lobur' ],
    publisher: 'Jones & Bartlett Publishers',
    publishedDate: '2014-02-01',
    description: 'Updated and revised to reflect the most current data in the field, perennial bestseller The Essentials of Computer Organization and Architecture, Fourth Edition is comprehensive enough to address all necessary organization and architecture topics, but concise enough to be appropriate for a single-term course. Its focus on real-world examples and practical applications encourages students to develop a "big-picture" understanding of how essential organization and architecture concepts are applied in the computing world. In addition to direct correlation with the ACM/IEEE CS2013 guidelines for computer organization and architecture, the text exposes readers to the inner workings of a modern digital computer through an integrated presentation of fundamental concepts and principles.The fully revised and updated Fourth Edition includes the most up-to-the-minute data and resources available and reflects current technologies, including tablets and cloud computing. All-new exercises, expanded discussions, and feature boxes in every chapter implement even more real-world applications and current data, and many chapters include all-new examples. A full suite of student and instructor resources, including a secure companion website, Lecture Outlines in PowerPoint Format, and an Instructor Manual, complement the text. This award-winning, best-selling text is the most thorough, student-friendly, and accessible text on the market today.Key Features:* The Fourth Edition is in direct correlation with the ACM/IEEE CS2013 guidelines for computer organization and architecture, in addition to integrating material from additional knowledge units. * All-new material on a variety of topics, including zetabytes and yottabytes, automatons, tablet computers, graphic processing units, and cloud computing* The MARIE Simulator package allows students to learn the essential concepts of computer organization and architecture, including assembly language, without getting caught up in unnecessary and confusing details.* Full suite of ancillary materials, including a secure companion website, PowerPoint lecture outlines, and an Instructor Manual* Bundled with an optional Intel supplement* Ideally suited for single-term courses',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 900,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    averageRating: 1,
    ratingsCount: 2,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: '3kQoAwAAQBAJ',
    link: 'http://books.google.com/books/about/The_Essentials_of_Computer_Organization.html?hl=&id=3kQoAwAAQBAJ',
    thumbnail: 'http://books.google.com/books/content?id=3kQoAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'The Computer and the Brain',
    authors: [ 'John von Neumann', 'Ray Kurzweil' ],
    publisher: 'Yale University Press',
    publishedDate: '2012-06-26',
    description: 'First published in 1958, John von Neumann\'s classic work "The Computer and the Brain" explored the analogies between computing machines and the living human brain. Von Neumann showed that the brain operates both digitally and analogically, but also has its own unique statistical language. And more than fifty years after its inception the "von Neumann architecture"--An organizational framework for computer design - still lies at the heart of today\'s machines. In his foreword to this new edition, Ray Kurzweil, a futurist famous for his own musings on the relationship between technology and consciousness, places von Neumann\'s work in a historical context and shows how it remains relevant today.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 83,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'hvPAUX0glAYC',
    link: 'http://books.google.com/books/about/The_Computer_and_the_Brain.html?hl=&id=hvPAUX0glAYC',
    thumbnail: 'http://books.google.com/books/content?id=hvPAUX0glAYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Computer Graphics',
    subtitle: 'Principles and Practice',
    authors:
     [ 'John F. Hughes',
       'Andries Van Dam',
       'James D. Foley',
       'Steven K. Feiner' ],
    publisher: 'Pearson Education',
    publishedDate: '2013',
    description: 'Computer Graphics: Principles and Practice, Third Edition, remains the most authoritative introduction to the field. The first edition, the original "Foley and van Dam," helped to define computer graphics and how it could be taught. The second edition became an even more comprehensive resource for practitioners and students alike. This third edition has been completely rewritten to provide detailed and up-to-date coverage of key concepts, algorithms, technologies, and applications. The authors explain the principles, as well as the mathematics, underlying computer graphics-knowledge that is essential for successful work both now and in the future. Early chapters show how to create 2D and 3D pictures right away, supporting experimentation. Later chapters, covering a broad range of topics, demonstrate more sophisticated approaches. Sections on current computer graphics practice show how to apply given principles in common situations, such as how to approximate an ideal solution on available hardware, or how to represent a data structure more efficiently. Topics are reinforced by exercises, program­ming problems, and hands-on projects. This revised edition features New coverage of the rendering equation, GPU architecture considerations, and importance- sampling in physically based rendering An emphasis on modern approaches, as in a new chapter on probability theory for use in Monte-Carlo rendering Implementations of GPU shaders, software rendering, and graphics-intensive 3D interfaces 3D real-time graphics platforms-their design goals and trade-offs-including new mobile and browser platforms Programming and debugging approaches unique to graphics development The text and hundreds of figures are presented in full color throughout the book. Programs are written in C++, C#, WPF, or pseudocode-whichever language is most effective for a given example. Source code and figures from the book, testbed programs, and additional content will be available from the authors\' website (cgpp.net) or the publisher\'s website (informit.com/title/9780321399526). Instructor resources will be available from the publisher. The wealth of information in this book makes it the essential resource for anyone working in or studying any aspect of computer graphics.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 1209,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'OVpsAQAAQBAJ',
    link: 'http://books.google.com/books/about/Computer_Graphics.html?hl=&id=OVpsAQAAQBAJ',
    thumbnail: 'http://books.google.com/books/content?id=OVpsAQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Hackers',
    subtitle: 'Heroes of the Computer Revolution - 25th Anniversary Edition',
    authors: [ 'Steven Levy' ],
    publisher: '"O\'Reilly Media, Inc."',
    publishedDate: '2010-05-19',
    description: 'This 25th anniversary edition of Steven Levy\'s classic book traces the exploits of the computer revolution\'s original hackers -- those brilliant and eccentric nerds from the late 1950s through the early \'80s who took risks, bent the rules, and pushed the world in a radical new direction. With updated material from noteworthy hackers such as Bill Gates, Mark Zuckerberg, Richard Stallman, and Steve Wozniak, Hackers is a fascinating story that begins in early computer research labs and leads to the first home computers. Levy profiles the imaginative brainiacs who found clever and unorthodox solutions to computer engineering problems. They had a shared sense of values, known as "the hacker ethic," that still thrives today. Hackers captures a seminal period in recent history when underground activities blazed a trail for today\'s digital world, from MIT students finagling access to clunky computer-card machines to the DIY culture that spawned the Altair and the Apple II.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 520,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    averageRating: 4,
    ratingsCount: 24,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'mShXzzKtpmEC',
    link: 'https://market.android.com/details?id=book-mShXzzKtpmEC',
    thumbnail: 'http://books.google.com/books/content?id=mShXzzKtpmEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'The Computer Book',
    subtitle: 'An Introduction to Computers and Computing',
    authors: [ 'Robin Bradbeer', 'Peter De Bono', 'Peter Laurie' ],
    publisher: 'London : British Broadcasting Corporation',
    publishedDate: '1982-01-01',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 208,
    printType: 'BOOK',
    categories: [ 'Computer programming' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'HbFrQgAACAAJ',
    link: 'http://books.google.com/books/about/The_Computer_Book.html?hl=&id=HbFrQgAACAAJ',
    thumbnail: undefined,
    images: {} },{ title: 'Science Fiction',
    subtitle: 'The 100 Best Novels : an English-language Selection, 1949-1984',
    authors: [ 'David Pringle' ],
    publisher: 'Carroll & Graf Pub',
    publishedDate: '1997',
    description: 'Recommends one hundred science fiction novels and offers a brief summary of each work',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 224,
    printType: 'BOOK',
    categories: [ 'Fiction' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'FYtvHQAACAAJ',
    link: 'http://books.google.com/books/about/Science_Fiction.html?hl=&id=FYtvHQAACAAJ',
    thumbnail: 'http://books.google.com/books/content?id=FYtvHQAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    images: {} },
  { title: 'Science Fiction',
    subtitle: 'The 100 Best Novels : an English-language Selection, 1949-1984',
    authors: [ 'David Pringle' ],
    publisher: 'Carroll & Graf Pub',
    publishedDate: '1985',
    description: 'Encompassing the masterpieces of modern science fiction this book offers a broad list of works by such authors as Ray Bradbury, George R. Stewart, and Gene Wolfe',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 224,
    printType: 'BOOK',
    categories: [ 'Literary Criticism' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'G7OHQgAACAAJ',
    link: 'http://books.google.com/books/about/Science_Fiction.html?hl=&id=G7OHQgAACAAJ',
    thumbnail: undefined,
    images: {} },
  { title: 'Golden Son',
    subtitle: 'Book II of The Red Rising Trilogy',
    authors: [ 'Pierce Brown' ],
    publisher: 'Del Rey',
    publishedDate: '2015-01-06',
    description: 'NEW YORK TIMES BESTSELLER • NAMED ONE OF THE BEST BOOKS OF THE YEAR BY NPR, BUZZFEED, AND BOOKLIST • With shades of The Hunger Games, Ender’s Game, and Game of Thrones, debut author Pierce Brown’s genre-defying epic Red Rising hit the ground running and wasted no time becoming a sensation. Golden Son continues the stunning saga of Darrow, a rebel forged by tragedy, battling to lead his oppressed people to freedom. As a Red, Darrow grew up working the mines deep beneath the surface of Mars, enduring backbreaking labor while dreaming of the better future he was building for his descendants. But the Society he faithfully served was built on lies. Darrow’s kind have been betrayed and denied by their elitist masters, the Golds—and their only path to liberation is revolution. And so Darrow sacrifices himself in the name of the greater good for which Eo, his true love and inspiration, laid down her own life. He becomes a Gold, infiltrating their privileged realm so that he can destroy it from within. A lamb among wolves in a cruel world, Darrow finds friendship, respect, and even love—but also the wrath of powerful rivals. To wage and win the war that will change humankind’s destiny, Darrow must confront the treachery arrayed against him, overcome his all-too-human desire for retribution—and strive not for violent revolt but a hopeful rebirth. Though the road ahead is fraught with danger and deceit, Darrow must choose to follow Eo’s principles of love and justice to free his people. He must live for more. BONUS: This edition includes an excerpt from Pierce Brown\'s Morning Star. Praise for Golden Son “Gripping . . . Both author and lead character have cranked up the emotional stakes. . . . With Golden Son, Brown avoids the sophomore slump, charging the novel with the kind of dystopia-toppling action you’d expect in a trilogy ender, not a middle volume. On virtually every level, this is a sequel that hates sequels—a perfect fit for a hero who already defies the tropes. [Grade:] A”—Entertainment Weekly “Stirring . . . Comparisons to The Hunger Games and Game of Thrones series are inevitable, for this tale has elements of both.”—Kirkus Reviews “Brown writes layered, flawed characters . . . but plot is his most breathtaking strength. . . . Every action seems to flow into the next.”—NPR “It’s a far superior sequel, in fact: one of the rare breed of reads that improves upon its predecessor in every conceivable category. . . . In a word, Golden Son is stunning. Never mind how little we’ve seen of 2015: Among science fiction fans, it should be a shoo-in for book of the year.”—Tor.com “Brown is a prodigy. As great as the first book of the Red Rising Trilogy is, Golden Son is even better. A wild ride full of suspense, intrigue, and serious ass-kicking bravado, it’s expertly written and emotionally engaging, with top-notch universe-building that begs for further exploration. I want more!”—Christopher Golden, New York Times bestselling author of Snowblind “The stakes are even higher than they were in Red Rising, and the twists and turns of the story are every bit as exciting. The jaw-dropper of an ending will leave readers hungry for the conclusion to Brown’s wholly original, completely thrilling saga.”—Booklist (starred review) “Dramatic . . . the rare middle book that loses almost no momentum as it sets up the final installment.”—Publishers Weekly',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 464,
    printType: 'BOOK',
    categories: [ 'Fiction' ],
    averageRating: 4.5,
    ratingsCount: 40,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'B4zIAgAAQBAJ',
    link: 'https://market.android.com/details?id=book-B4zIAgAAQBAJ',
    thumbnail: 'http://books.google.com/books/content?id=B4zIAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Coyote',
    authors: [ 'Allen Steele' ],
    publisher: 'Penguin',
    publishedDate: '2002-11-05',
    description: 'Coyote marks a dramatic new turn in the career of Allen Steele, Hugo Award-winning author of Chronospace. Epic in scope, passionate in its conviction, and set against a backdrop of plausible events, it tells the brilliant story of Earth’s first interstellar colonists—and the mysterious planet that becomes their home…',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 448,
    printType: 'BOOK',
    categories: [ 'Fiction' ],
    averageRating: 4,
    ratingsCount: 12,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: '97lw2quFk1YC',
    link: 'https://market.android.com/details?id=book-97lw2quFk1YC',
    thumbnail: 'http://books.google.com/books/content?id=97lw2quFk1YC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'The Way of Kings',
    authors: [ 'Brandon Sanderson' ],
    publisher: 'Macmillan',
    publishedDate: '2010-08-31',
    description: 'From #1 New York Times bestselling author Brandon Sanderson, The Way of Kings, Book One of the Stormlight Archive begins an incredible new saga of epic proportion. Roshar is a world of stone and storms. Uncanny tempests of incredible power sweep across the rocky terrain so frequently that they have shaped ecology and civilization alike. Animals hide in shells, trees pull in branches, and grass retracts into the soilless ground. Cities are built only where the topography offers shelter. It has been centuries since the fall of the ten consecrated orders known as the Knights Radiant, but their Shardblades and Shardplate remain: mystical swords and suits of armor that transform ordinary men into near-invincible warriors. Men trade kingdoms for Shardblades. Wars were fought for them, and won by them. One such war rages on a ruined landscape called the Shattered Plains. There, Kaladin, who traded his medical apprenticeship for a spear to protect his little brother, has been reduced to slavery. In a war that makes no sense, where ten armies fight separately against a single foe, he struggles to save his men and to fathom the leaders who consider them expendable. Brightlord Dalinar Kholin commands one of those other armies. Like his brother, the late king, he is fascinated by an ancient text called The Way of Kings. Troubled by over-powering visions of ancient times and the Knights Radiant, he has begun to doubt his own sanity. Across the ocean, an untried young woman named Shallan seeks to train under an eminent scholar and notorious heretic, Dalinar\'s niece, Jasnah. Though she genuinely loves learning, Shallan\'s motives are less than pure. As she plans a daring theft, her research for Jasnah hints at secrets of the Knights Radiant and the true cause of the war. The result of over ten years of planning, writing, and world-building, The Way of Kings is but the opening movement of the Stormlight Archive, a bold masterpiece in the making. Speak again the ancient oaths: Life before death. Strength before weakness. Journey before Destination. and return to men the Shards they once bore. The Knights Radiant must stand again. The Cosmere The Mistborn series Mistborn: The Final Empire The Well of Ascension The Hero of Ages Alloy of Law Shadows of Self Bands of Mourning The Stormlight Archive The Way of Kings Words of Radiance Edgedancer (Novella) Oathbringer (forthcoming) Collection Arcanum Unbounded Other Cosmere Titles Elantris Warbreaker Rithmatist The Alcatraz vs. the Evil Librarians series Alcatraz vs. the Evil Librarians The Scrivener\'s Bones The Knights of Crystallia The Shattered Lens The Dark Talent The Reckoners Steelheart Firefight Calamity At the Publisher\'s request, this title is being sold without Digital Rights Management Software (DRM) applied.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 1008,
    printType: 'BOOK',
    categories: [ 'Fiction' ],
    averageRating: 4.5,
    ratingsCount: 208,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'OHclhBVv-X4C',
    link: 'https://market.android.com/details?id=book-OHclhBVv-X4C',
    thumbnail: 'http://books.google.com/books/content?id=OHclhBVv-X4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'MaddAddam',
    subtitle: 'Book 3 of The MaddAddam Trilogy',
    authors: [ 'Margaret Atwood' ],
    publisher: 'Anchor',
    publishedDate: '2013-09-03',
    description: 'A New York Times Notable Book A Washington Post Notable Book A Best Book of the Year: The Guardian, NPR, The Christian Science Monitor, The Globe and Mail A GoodReads Reader\'s Choice Bringing together Oryx and Crake and The Year of the Flood, this thrilling conclusion to Margaret Atwood\'s speculative fiction trilogy points toward the ultimate endurance of community, and love. Months after the Waterless Flood pandemic has wiped out most of humanity, Toby and Ren have rescued their friend Amanda from the vicious Painballers. They return to the MaddAddamite cob house, newly fortified against man and giant pigoon alike. Accompanying them are the Crakers, the gentle, quasi-human species engineered by the brilliant but deceased Crake. Their reluctant prophet, Snowman-the-Jimmy, is recovering from a debilitating fever, so it\'s left to Toby to preach the Craker theology, with Crake as Creator. She must also deal with cultural misunderstandings, terrible coffee, and her jealousy over her lover, Zeb. Zeb has been searching for Adam One, founder of the God\'s Gardeners, the pacifist green religion from which Zeb broke years ago to lead the MaddAddamites in active resistance against the destructive CorpSeCorps. But now, under threat of a Painballer attack, the MaddAddamites must fight back with the aid of their newfound allies, some of whom have four trotters. At the center of MaddAddam is the story of Zeb\'s dark and twisted past, which contains a lost brother, a hidden murder, a bear, and a bizarre act of revenge. Combining adventure, humor, romance, superb storytelling, and an imagination at once dazzlingly inventive and grounded in a recognizable world, MaddAddam is vintage Margaret Atwood—a moving and dramatic conclusion to her internationally celebrated dystopian trilogy. From the Hardcover edition.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 416,
    printType: 'BOOK',
    categories: [ 'Fiction' ],
    averageRating: 3.5,
    ratingsCount: 56,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: '9FlmLA3_ficC',
    link: 'https://market.android.com/details?id=book-9FlmLA3_ficC',
    thumbnail: 'http://books.google.com/books/content?id=9FlmLA3_ficC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'The Three-Body Problem',
    authors: [ 'Cixin Liu' ],
    publisher: 'Macmillan',
    publishedDate: '2014-11-11',
    description: 'The Three-Body Problem is the first chance for English-speaking readers to experience this multiple award winning phenomenon from China\'s most beloved science fiction author, Liu Cixin. Set against the backdrop of China\'s Cultural Revolution, a secret military project sends signals into space to establish contact with aliens. An alien civilization on the brink of destruction captures the signal and plans to invade Earth. Meanwhile, on Earth, different camps start forming, planning to either welcome the superior beings and help them take over a world seen as corrupt, or to fight against the invasion. The result is a science fiction masterpiece of enormous scope and vision. At the Publisher\'s request, this title is being sold without Digital Rights Management Software (DRM) applied.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 400,
    printType: 'BOOK',
    categories: [ 'Fiction' ],
    averageRating: 3.5,
    ratingsCount: 19,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'ZrNzAwAAQBAJ',
    link: 'https://market.android.com/details?id=book-ZrNzAwAAQBAJ',
    thumbnail: 'http://books.google.com/books/content?id=ZrNzAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Earth vs. the Sci-Fi Filmmakers',
    subtitle: '20 Interviews',
    authors: [ 'Tom Weaver' ],
    publisher: 'McFarland',
    publishedDate: '2014-06-23',
    description: "Perhaps no film genres attracted more rabid fans and less critical acclaim than the horror and science fiction movies of the 1950s and 1960s. The men and women who made the characters come to life are interviewed here, talking about their work, the behind",
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 396,
    printType: 'BOOK',
    categories: [ 'Performing Arts' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'kGLtcc_pJxQC',
    link: 'https://market.android.com/details?id=book-kGLtcc_pJxQC',
    thumbnail: 'http://books.google.com/books/content?id=kGLtcc_pJxQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Sci-Fi a la Mode',
    authors: [ 'Pj Belanger' ],
    publisher: 'Pj Belanger',
    publishedDate: '2009-12-01',
    description: 'A series of Short Stories in the tradition of classic Science Fiction.',
    industryIdentifiers: [ [Object], [Object] ],
    printType: 'BOOK',
    categories: [ 'Fiction' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'Y3MlMC0PCEQC',
    link: 'https://market.android.com/details?id=book-Y3MlMC0PCEQC',
    thumbnail: 'http://books.google.com/books/content?id=Y3MlMC0PCEQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Jewish Sci-fi Stories for Kids',
    authors: [ 'Yaacov Peterseil' ],
    publisher: 'Devora Publishing',
    publishedDate: '1999',
    description: 'Here are science fiction stories that bend and twist the limits of imagination. Best of all they have a yiddishe taam, a taste of the Jewish supernatural.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 190,
    printType: 'BOOK',
    categories: [ 'Juvenile Fiction' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'UHHS17mfVb4C',
    link: 'http://books.google.com/books/about/Jewish_Sci_fi_Stories_for_Kids.html?hl=&id=UHHS17mfVb4C',
    thumbnail: 'http://books.google.com/books/content?id=UHHS17mfVb4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },{ title: 'Bodies in Technology',
    authors: [ 'Don Ihde' ],
    publisher: 'U of Minnesota Press',
    publishedDate: '2002',
    description: 'New technologies suggest new ideas about embodiment - our \'reach\' extends to global sites through the Internet; we enter cyberspace through the engines of virtual reality. In this book, a leading philosopher of technology explores the meaning of bodies in technology—how the sense of our bodies and of our orientation in the world is affected by the various information technologies. \'Bodies in Technology\' begins with an analysis of embodiment in cyberspace, then moves on to consider ways in which social theorists have interpreted or overlooked these conditions. An astute and sensible judge of these theories, Don Ihde is a uniquely provocative and helpful guide through contemporary thinking about technology and embodiment, drawing on sources and examples as various as video games, popular films, the workings of e-mail, and virtual reality techniques. Charting the historical, philosophical, and practical territory between virtual reality and real life, this work is an important contribution to the national conversation on the impact technology-and information technology in particular-has on our lives in a wired, global age.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 155,
    printType: 'BOOK',
    categories: [ 'Technology & Engineering' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'kLM9gfnPcFAC',
    link: 'http://books.google.com/books/about/Bodies_in_Technology.html?hl=&id=kLM9gfnPcFAC',
    thumbnail: 'http://books.google.com/books/content?id=kLM9gfnPcFAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'The Physics of Information Technology',
    authors: [ 'Neil Gershenfeld' ],
    publisher: 'Cambridge University Press',
    publishedDate: '2000-10-16',
    description: 'A companion volume to the best-selling The Nature of Mathematical Modeling from the same author, first published in 2000.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 370,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    averageRating: 5,
    ratingsCount: 3,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: '22dZsOVFwrUC',
    link: 'http://books.google.com/books/about/The_Physics_of_Information_Technology.html?hl=&id=22dZsOVFwrUC',
    thumbnail: 'http://books.google.com/books/content?id=22dZsOVFwrUC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'The Book',
    subtitle: 'The Life Story of a Technology',
    authors: [ 'Nicole Howard' ],
    publisher: 'Greenwood Publishing Group',
    publishedDate: '2005',
    description: 'Introduces the history of the book, beginning with papyrus in ancient Egypt, through the development of the printing press, to current computer-based technologies, including its influence on societies and cultures around the world.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 171,
    printType: 'BOOK',
    categories: [ 'History' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: '4WwdMJKXzhEC',
    link: 'https://market.android.com/details?id=book-4WwdMJKXzhEC',
    thumbnail: 'http://books.google.com/books/content?id=4WwdMJKXzhEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Technology and Social Inclusion',
    subtitle: 'Rethinking the Digital Divide',
    authors: [ 'Mark Warschauer' ],
    publisher: 'MIT Press',
    publishedDate: '2004',
    description: 'Going beyond the oversimplified notion of a "digital divide" to analyze the relationship between access to information and communication technologies and social inclusion.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 260,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'nU4zz1O88mAC',
    link: 'http://books.google.com/books/about/Technology_and_Social_Inclusion.html?hl=&id=nU4zz1O88mAC',
    thumbnail: 'http://books.google.com/books/content?id=nU4zz1O88mAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Theory Of Technology',
    authors: [ 'David Clarke' ],
    publisher: 'Transaction Publishers',
    description: 'The history of technology is often troubled by good ideas that do not, for one reason or another, take off right away--sometimes for millennia. Sometimes, technology comes to a standstill, and sometimes, it even reverses itself. Thus, unlike science, which seems to proceed at a reasonable and calm rate, the progress of technology is difficult to theorize about. While in science many developments are predictable to a certain extent and this predictability may, at times, direct or stymie science\'s progress--as with stem-cell research and cloning--technological advances, such as the Internet, are often sudden and unpredictable, and therefore frightening. In "Theory of Technology," David Clarke brings together nine authors who try to understand technology from a variety of viewpoints. Rias van Wyk, in "Technology," parses the concept into many angles, including its anatomy, taxonomy, and evolution. Karol Pelc, in "Knowledge Mapping," discusses tracking the evolution of the emerging discipline of technology management. Jon Beard, in "Management of Technology," pursues a similar mapping endeavor, but looks to the patterns of the "literature" of technology management. Thomas Clarke, in "Unique Features of an R&D Work Environment and Research Scientists and Engineers," takes the reader on a tour of how people of technology present unique challenges to not just management but whole organizations. Richard Howey, in "Understanding Software Technology," places enterprise software into a meaningful pattern of technology management. Fred Foldvary and Daniel Klein, in "The Half-Life of Policy Rationales," discuss how new technology affects old policy issues. John Cogan, in "Some Philosophical Thoughts on the Nature of Technology," maintains that our Aristotelian search for the essence of technology is doomed. And Peter Bond, in "The Biology of Technology," establishes a basis for the development of a socio-biological approach to understanding the phenomena of technological society and technical change. ""Theory of Technology" is an important book. It recognizes the near impossibility of forecasting technological progress, or of planning the trajectory that a new technology may take. It goes beyond other studies in showing how understanding of the nature of technology itself is the necessary first step in removing levels of uncertainty from charting those trajectories as they impact our daily lives."-Paul Ceruzzi, curator, Aerospace Electronics and Computing, National Air and Space Museum, Smithsonian Institution "Unstuffy. ["Theory of Technology" is] a sheltered workshop for the atheoretical in technology studies." -Russell Maulitz, Department of Family, Community and Preventive Medicine, Drexel University College of Medicine "Technology is one of those words whose meaning and importance we intuitively know, but have trouble defining and fully understanding. Technology is becoming ever more ubiquitous in our lives and economies, and harnessing it in predictable ways ever more important. "Theory of Technology" goes a long way toward building a framework of analysis and perspective to overcome these limitations, and thus toward helping us bring order to our thinking and our ability to employ in orderly ways one of the keys to contemporary life." -Thomas J. Duesterberg, President and CEO, Manufacturers ""Theory of Technology" is an excellent and challenging introduction to the field-also for the uninitiated. It offers a history of the discipline, of its attempts to better understand the nature of technology from, among others, philosophical and biological perspectives, and discusses the management of technology and its policy consequences. In also analyzing the semantics of technology theory and practice-a brave enterprise in these days of fads and fashions in wordings and phrases-it not only seeks the (self-)discipline that is needed to support the scientific status of the field but may indeed help increase actual influence on technology practice and policy." -Marie-Louise Bemelmans-Videc, professor of public administration, Radboud University Nijmegen, The Netherlands "David Clarke\'s new book about the "Theory of Technology" is the most comprehensive, multifaceted, and challenging treatment of the subject to date. It also makes a very interesting read. Instead of looking at technology from the perspective of just one author, Mr. Clarke has chosen to ask some of the most respected and provocative experts in the field to look at technology from a variety of major angles that nicely and completely encircle and illuminate the subject. I don\'t think there is an aspect of modern technology that isn\'t covered in an entertaining and informative fashion. My profession as a patent attorney puts me in direct, daily contact with the practical aspects of all new technologies. Mr. Clarke\'s well organized and enjoyable book has helped me appreciate the bigger context of my work. It will stay on the bookshelf in my office in the company of just a handful of other books that give me a better understanding about the world in which we live." -R. C. Woodbridge, Princeton, NJ "Technology is one of those words whose meaning and importance we intuitively know, but have trouble defining and fully understanding. Technology is becoming ever more ubiquitous in our lives and economies, and harnessing it in predictable ways ever more important. "Theory of Technology" goes a long way toward building a framework of analysis and perspective to overcome these limitations, and thus toward helping us bring order to our thinking and our ability to employ in orderly ways one of the keys to contemporary life." -Thomas J. Duesterberg, President and CEO, Manufacturers Alliance/MAPI David Clarke, professor emeritus at Southern Illinois University, has degrees in philosophy, architecture, management science, and urban design. His is the editor of "Technology and Terrorism," published by Transaction, as well as the editor of the Transaction journal "Knowledge, Technology, & Policy."',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 159,
    printType: 'BOOK',
    categories: [ 'Technology & Engineering' ],
    averageRating: 5,
    ratingsCount: 1,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'beiUC_jUaTwC',
    link: 'https://market.android.com/details?id=book-beiUC_jUaTwC',
    thumbnail: 'http://books.google.com/books/content?id=beiUC_jUaTwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'The Technology of Orgasm',
    subtitle: 'Hysteria the Vibrator, and Womens Sexual Satisfaction',
    authors: [ 'Rachel P. Maines' ],
    publisher: 'JHU Press',
    publishedDate: '2001-03-01',
    description: 'The author explores hysteria in Western medicine throughout the ages and examines the characterization of female sexuality as a disease requiring treatment. Medical authorities, she writes, were able to defend and justify the clinical production of orgasm in women as necessary to maintain the dominant view of sexuality, which defined sex as penetration to male orgasm - a practice that consistently fails to produce orgasm in a majority of the female population. This male-centered definition of satisfying and healthy coitus shaped not only the development of concepts of female sexual pathology but also the instrumentation designed to cope with them.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 181,
    printType: 'BOOK',
    categories: [ 'Science' ],
    averageRating: 4,
    ratingsCount: 1,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'iNKw0XuaSxoC',
    link: 'http://books.google.com/books/about/The_Technology_of_Orgasm.html?hl=&id=iNKw0XuaSxoC',
    thumbnail: 'http://books.google.com/books/content?id=iNKw0XuaSxoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Science, Technology, and Society',
    subtitle: 'An Encyclopedia',
    authors: [ 'Sal P. Restivo' ],
    publisher: 'Oxford University Press on Demand',
    publishedDate: '2005',
    description: '\'Science, Technology, and Society\' offers approximately 150 articles written by major scholars and experts from academic and scientific institutions worldwide. The theme is the functions and effects of science and technology in society and culture.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 701,
    printType: 'BOOK',
    categories: [ 'Social Science' ],
    averageRating: 5,
    ratingsCount: 1,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'A8C3m8rRba4C',
    link: 'http://books.google.com/books/about/Science_Technology_and_Society.html?hl=&id=A8C3m8rRba4C',
    thumbnail: 'http://books.google.com/books/content?id=A8C3m8rRba4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Children, Technology, and Culture',
    subtitle: 'The Impacts of Technologies in Children\'s Everyday Lives',
    authors:
     [ 'Phil Mizen',
       'Ian Hutchby',
       'Christopher John Pole',
       'Jo Moran-Ellis',
       'Angela Bolton' ],
    publisher: 'Psychology Press',
    publishedDate: '2001',
    description: 'Childhood is increasingly saturated by technology: from television to the Internet, video games to \'video nasties\', camcorders to personal computers. Children, Technology and Culture looks at the interplay of children and technology which poses critical questions for how we understand the nature of childhood in late modern society. This collection brings together researchers from a range of disciplines to address the following four aspects of this relationship between children and technology: *children\'s access to technologies and the implications for social relationships *the structural contexts of children\'s engagement with technologies with a focus on gender and the family *the situatedness of children\'s interactions with technological objects *the constitution of children and childhood through the mediations of technology _ This book represents a substantial contribution to contemporary social scientific thinking both about the nature of children and childhood, the social impacts of technologies and the various relationships between the two.',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 189,
    printType: 'BOOK',
    categories: [ 'Education' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'NOfSHdweFLsC',
    link: 'http://books.google.com/books/about/Children_Technology_and_Culture.html?hl=&id=NOfSHdweFLsC',
    thumbnail: 'http://books.google.com/books/content?id=NOfSHdweFLsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Handbook of Display Technology',
    authors: [ 'Joseph A. Castellano' ],
    publisher: 'Gulf Professional Publishing',
    publishedDate: '1992',
    description: 'This book presents a comprehensive review of technical and commercial aspects of display technology. It provides design engineers with the information needed to select proper technology for new products. The book focuses on flat, thin displays such as light-emitting diodes, plasma display panels, and liquid crystal displays, but it also includes material on cathode ray tubes. Displays include a large number of products from televisions, auto dashboards, radios, and household appliances, to gasoline pumps, heart monitors, microwave ovens, and more. For more information on display technology, go to the experts: http://www.insightmedia.info/',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 341,
    printType: 'BOOK',
    categories: [ 'Computers' ],
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'p68XfA0MHpoC',
    link: 'http://books.google.com/books/about/Handbook_of_Display_Technology.html?hl=&id=p68XfA0MHpoC',
    thumbnail: 'http://books.google.com/books/content?id=p68XfA0MHpoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
  { title: 'Open Innovation',
    subtitle: 'The New Imperative for Creating and Profiting from Technology',
    authors: [ 'Henry William Chesbrough' ],
    publisher: 'Harvard Business Press',
    publishedDate: '2006',
    description: 'The information revolution has made for a radically more fluid knowledge environment, and the growth of venture capital has created inexorable pressure towards fast commercialisation of existing technologies Companies that don\'t use the technologies they develop are likely to lose them. Key features Over the past several years, Hank Chesbrough has done excellent research and writing on the commercialisation of technology and the changing role and context for R&D. This book represents a powerful synthesis of that work in the form of a new paradigm for managing corporate research and bringing new technologies to market Chesbrough impressively articulates his ideas and how they connect to each other, weaving several disparate areas of work R&D, corporate venturing, spinoffs, licensing and intellectual property into a single coherent framework',
    industryIdentifiers: [ [Object], [Object] ],
    pageCount: 227,
    printType: 'BOOK',
    categories: [ 'Business & Economics' ],
    averageRating: 4,
    ratingsCount: 11,
    maturityRating: 'NOT_MATURE',
    language: 'en',
    id: 'OeLIH89YiMcC',
    link: 'http://books.google.com/books/about/Open_Innovation.html?hl=&id=OeLIH89YiMcC',
    thumbnail: 'http://books.google.com/books/content?id=OeLIH89YiMcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    images: {} },
     { title: 'MaddAddam',
        subtitle: 'Book 3 of The MaddAddam Trilogy',
        authors: [ 'Margaret Atwood' ],
        publisher: 'Anchor',
        publishedDate: '2013-09-03',
        description: 'A New York Times Notable Book A Washington Post Notable Book A Best Book of the Year: The Guardian, NPR, The Christian Science Monitor, The Globe and Mail A GoodReads Reader\'s Choice Bringing together Oryx and Crake and The Year of the Flood, this thrilling conclusion to Margaret Atwood\'s speculative fiction trilogy points toward the ultimate endurance of community, and love. Months after the Waterless Flood pandemic has wiped out most of humanity, Toby and Ren have rescued their friend Amanda from the vicious Painballers. They return to the MaddAddamite cob house, newly fortified against man and giant pigoon alike. Accompanying them are the Crakers, the gentle, quasi-human species engineered by the brilliant but deceased Crake. Their reluctant prophet, Snowman-the-Jimmy, is recovering from a debilitating fever, so it\'s left to Toby to preach the Craker theology, with Crake as Creator. She must also deal with cultural misunderstandings, terrible coffee, and her jealousy over her lover, Zeb. Zeb has been searching for Adam One, founder of the God\'s Gardeners, the pacifist green religion from which Zeb broke years ago to lead the MaddAddamites in active resistance against the destructive CorpSeCorps. But now, under threat of a Painballer attack, the MaddAddamites must fight back with the aid of their newfound allies, some of whom have four trotters. At the center of MaddAddam is the story of Zeb\'s dark and twisted past, which contains a lost brother, a hidden murder, a bear, and a bizarre act of revenge. Combining adventure, humor, romance, superb storytelling, and an imagination at once dazzlingly inventive and grounded in a recognizable world, MaddAddam is vintage Margaret Atwood—a moving and dramatic conclusion to her internationally celebrated dystopian trilogy. From the Hardcover edition.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 416,
        printType: 'BOOK',
        categories: [ 'Fiction' ],
        averageRating: 3.5,
        ratingsCount: 56,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: '9FlmLA3_ficC',
        link: 'https://market.android.com/details?id=book-9FlmLA3_ficC',
        thumbnail: 'http://books.google.com/books/content?id=9FlmLA3_ficC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'The Three-Body Problem',
        authors: [ 'Cixin Liu' ],
        publisher: 'Macmillan',
        publishedDate: '2014-11-11',
        description: 'The Three-Body Problem is the first chance for English-speaking readers to experience this multiple award winning phenomenon from China\'s most beloved science fiction author, Liu Cixin. Set against the backdrop of China\'s Cultural Revolution, a secret military project sends signals into space to establish contact with aliens. An alien civilization on the brink of destruction captures the signal and plans to invade Earth. Meanwhile, on Earth, different camps start forming, planning to either welcome the superior beings and help them take over a world seen as corrupt, or to fight against the invasion. The result is a science fiction masterpiece of enormous scope and vision. At the Publisher\'s request, this title is being sold without Digital Rights Management Software (DRM) applied.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 400,
        printType: 'BOOK',
        categories: [ 'Fiction' ],
        averageRating: 3.5,
        ratingsCount: 19,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'ZrNzAwAAQBAJ',
        link: 'https://market.android.com/details?id=book-ZrNzAwAAQBAJ',
        thumbnail: 'http://books.google.com/books/content?id=ZrNzAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Earth vs. the Sci-Fi Filmmakers',
        subtitle: '20 Interviews',
        authors: [ 'Tom Weaver' ],
        publisher: 'McFarland',
        publishedDate: '2014-06-23',
        description: '"Perhaps no film genres attracted more rabid fans and less critical acclaim than the horror and science fiction movies of the 1950s and 1960s. The men and women who made the characters come to life are interviewed here, talking about their work, the behin',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 396,
        printType: 'BOOK',
        categories: [ 'Performing Arts' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'kGLtcc_pJxQC',
        link: 'https://market.android.com/details?id=book-kGLtcc_pJxQC',
        thumbnail: 'http://books.google.com/books/content?id=kGLtcc_pJxQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Sci-Fi a la Mode',
        authors: [ 'Pj Belanger' ],
        publisher: 'Pj Belanger',
        publishedDate: '2009-12-01',
        description: 'A series of Short Stories in the tradition of classic Science Fiction.',
        industryIdentifiers: [ [Object], [Object] ],
        printType: 'BOOK',
        categories: [ 'Fiction' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'Y3MlMC0PCEQC',
        link: 'https://market.android.com/details?id=book-Y3MlMC0PCEQC',
        thumbnail: 'http://books.google.com/books/content?id=Y3MlMC0PCEQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Jewish Sci-fi Stories for Kids',
        authors: [ 'Yaacov Peterseil' ],
        publisher: 'Devora Publishing',
        publishedDate: '1999',
        description: 'Here are science fiction stories that bend and twist the limits of imagination. Best of all they have a yiddishe taam, a taste of the Jewish supernatural.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 190,
        printType: 'BOOK',
        categories: [ 'Juvenile Fiction' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'UHHS17mfVb4C',
        link: 'http://books.google.com/books/about/Jewish_Sci_fi_Stories_for_Kids.html?hl=&id=UHHS17mfVb4C',
        thumbnail: 'http://books.google.com/books/content?id=UHHS17mfVb4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
         { title: 'Bodies in Technology',
        authors: [ 'Don Ihde' ],
        publisher: 'U of Minnesota Press',
        publishedDate: '2002',
        description: 'New technologies suggest new ideas about embodiment - our \'reach\' extends to global sites through the Internet; we enter cyberspace through the engines of virtual reality. In this book, a leading philosopher of technology explores the meaning of bodies in technology—how the sense of our bodies and of our orientation in the world is affected by the various information technologies. \'Bodies in Technology\' begins with an analysis of embodiment in cyberspace, then moves on to consider ways in which social theorists have interpreted or overlooked these conditions. An astute and sensible judge of these theories, Don Ihde is a uniquely provocative and helpful guide through contemporary thinking about technology and embodiment, drawing on sources and examples as various as video games, popular films, the workings of e-mail, and virtual reality techniques. Charting the historical, philosophical, and practical territory between virtual reality and real life, this work is an important contribution to the national conversation on the impact technology-and information technology in particular-has on our lives in a wired, global age.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 155,
        printType: 'BOOK',
        categories: [ 'Technology & Engineering' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'kLM9gfnPcFAC',
        link: 'http://books.google.com/books/about/Bodies_in_Technology.html?hl=&id=kLM9gfnPcFAC',
        thumbnail: 'http://books.google.com/books/content?id=kLM9gfnPcFAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'The Physics of Information Technology',
        authors: [ 'Neil Gershenfeld' ],
        publisher: 'Cambridge University Press',
        publishedDate: '2000-10-16',
        description: 'A companion volume to the best-selling The Nature of Mathematical Modeling from the same author, first published in 2000.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 370,
        printType: 'BOOK',
        categories: [ 'Computers' ],
        averageRating: 5,
        ratingsCount: 3,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: '22dZsOVFwrUC',
        link: 'http://books.google.com/books/about/The_Physics_of_Information_Technology.html?hl=&id=22dZsOVFwrUC',
        thumbnail: 'http://books.google.com/books/content?id=22dZsOVFwrUC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'The Book',
        subtitle: 'The Life Story of a Technology',
        authors: [ 'Nicole Howard' ],
        publisher: 'Greenwood Publishing Group',
        publishedDate: '2005',
        description: 'Introduces the history of the book, beginning with papyrus in ancient Egypt, through the development of the printing press, to current computer-based technologies, including its influence on societies and cultures around the world.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 171,
        printType: 'BOOK',
        categories: [ 'History' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: '4WwdMJKXzhEC',
        link: 'https://market.android.com/details?id=book-4WwdMJKXzhEC',
        thumbnail: 'http://books.google.com/books/content?id=4WwdMJKXzhEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Technology and Social Inclusion',
        subtitle: 'Rethinking the Digital Divide',
        authors: [ 'Mark Warschauer' ],
        publisher: 'MIT Press',
        publishedDate: '2004',
        description: 'Going beyond the oversimplified notion of a "digital divide" to analyze the relationship between access to information and communication technologies and social inclusion.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 260,
        printType: 'BOOK',
        categories: [ 'Computers' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'nU4zz1O88mAC',
        link: 'http://books.google.com/books/about/Technology_and_Social_Inclusion.html?hl=&id=nU4zz1O88mAC',
        thumbnail: 'http://books.google.com/books/content?id=nU4zz1O88mAC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Theory Of Technology',
        authors: [ 'David Clarke' ],
        publisher: 'Transaction Publishers',
        description: 'The history of technology is often troubled by good ideas that do not, for one reason or another, take off right away--sometimes for millennia. Sometimes, technology comes to a standstill, and sometimes, it even reverses itself. Thus, unlike science, which seems to proceed at a reasonable and calm rate, the progress of technology is difficult to theorize about. While in science many developments are predictable to a certain extent and this predictability may, at times, direct or stymie science\'s progress--as with stem-cell research and cloning--technological advances, such as the Internet, are often sudden and unpredictable, and therefore frightening. In "Theory of Technology," David Clarke brings together nine authors who try to understand technology from a variety of viewpoints. Rias van Wyk, in "Technology," parses the concept into many angles, including its anatomy, taxonomy, and evolution. Karol Pelc, in "Knowledge Mapping," discusses tracking the evolution of the emerging discipline of technology management. Jon Beard, in "Management of Technology," pursues a similar mapping endeavor, but looks to the patterns of the "literature" of technology management. Thomas Clarke, in "Unique Features of an R&D Work Environment and Research Scientists and Engineers," takes the reader on a tour of how people of technology present unique challenges to not just management but whole organizations. Richard Howey, in "Understanding Software Technology," places enterprise software into a meaningful pattern of technology management. Fred Foldvary and Daniel Klein, in "The Half-Life of Policy Rationales," discuss how new technology affects old policy issues. John Cogan, in "Some Philosophical Thoughts on the Nature of Technology," maintains that our Aristotelian search for the essence of technology is doomed. And Peter Bond, in "The Biology of Technology," establishes a basis for the development of a socio-biological approach to understanding the phenomena of technological society and technical change. ""Theory of Technology" is an important book. It recognizes the near impossibility of forecasting technological progress, or of planning the trajectory that a new technology may take. It goes beyond other studies in showing how understanding of the nature of technology itself is the necessary first step in removing levels of uncertainty from charting those trajectories as they impact our daily lives."-Paul Ceruzzi, curator, Aerospace Electronics and Computing, National Air and Space Museum, Smithsonian Institution "Unstuffy. ["Theory of Technology" is] a sheltered workshop for the atheoretical in technology studies." -Russell Maulitz, Department of Family, Community and Preventive Medicine, Drexel University College of Medicine "Technology is one of those words whose meaning and importance we intuitively know, but have trouble defining and fully understanding. Technology is becoming ever more ubiquitous in our lives and economies, and harnessing it in predictable ways ever more important. "Theory of Technology" goes a long way toward building a framework of analysis and perspective to overcome these limitations, and thus toward helping us bring order to our thinking and our ability to employ in orderly ways one of the keys to contemporary life." -Thomas J. Duesterberg, President and CEO, Manufacturers ""Theory of Technology" is an excellent and challenging introduction to the field-also for the uninitiated. It offers a history of the discipline, of its attempts to better understand the nature of technology from, among others, philosophical and biological perspectives, and discusses the management of technology and its policy consequences. In also analyzing the semantics of technology theory and practice-a brave enterprise in these days of fads and fashions in wordings and phrases-it not only seeks the (self-)discipline that is needed to support the scientific status of the field but may indeed help increase actual influence on technology practice and policy." -Marie-Louise Bemelmans-Videc, professor of public administration, Radboud University Nijmegen, The Netherlands "David Clarke\'s new book about the "Theory of Technology" is the most comprehensive, multifaceted, and challenging treatment of the subject to date. It also makes a very interesting read. Instead of looking at technology from the perspective of just one author, Mr. Clarke has chosen to ask some of the most respected and provocative experts in the field to look at technology from a variety of major angles that nicely and completely encircle and illuminate the subject. I don\'t think there is an aspect of modern technology that isn\'t covered in an entertaining and informative fashion. My profession as a patent attorney puts me in direct, daily contact with the practical aspects of all new technologies. Mr. Clarke\'s well organized and enjoyable book has helped me appreciate the bigger context of my work. It will stay on the bookshelf in my office in the company of just a handful of other books that give me a better understanding about the world in which we live." -R. C. Woodbridge, Princeton, NJ "Technology is one of those words whose meaning and importance we intuitively know, but have trouble defining and fully understanding. Technology is becoming ever more ubiquitous in our lives and economies, and harnessing it in predictable ways ever more important. "Theory of Technology" goes a long way toward building a framework of analysis and perspective to overcome these limitations, and thus toward helping us bring order to our thinking and our ability to employ in orderly ways one of the keys to contemporary life." -Thomas J. Duesterberg, President and CEO, Manufacturers Alliance/MAPI David Clarke, professor emeritus at Southern Illinois University, has degrees in philosophy, architecture, management science, and urban design. His is the editor of "Technology and Terrorism," published by Transaction, as well as the editor of the Transaction journal "Knowledge, Technology, & Policy."',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 159,
        printType: 'BOOK',
        categories: [ 'Technology & Engineering' ],
        averageRating: 5,
        ratingsCount: 1,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'beiUC_jUaTwC',
        link: 'https://market.android.com/details?id=book-beiUC_jUaTwC',
        thumbnail: 'http://books.google.com/books/content?id=beiUC_jUaTwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'The Technology of Orgasm',
        subtitle: '"Hysteria," the Vibrator, and Women\'s Sexual Satisfaction',
        authors: [ 'Rachel P. Maines' ],
        publisher: 'JHU Press',
        publishedDate: '2001-03-01',
        description: 'The author explores hysteria in Western medicine throughout the ages and examines the characterization of female sexuality as a disease requiring treatment. Medical authorities, she writes, were able to defend and justify the clinical production of orgasm in women as necessary to maintain the dominant view of sexuality, which defined sex as penetration to male orgasm - a practice that consistently fails to produce orgasm in a majority of the female population. This male-centered definition of satisfying and healthy coitus shaped not only the development of concepts of female sexual pathology but also the instrumentation designed to cope with them.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 181,
        printType: 'BOOK',
        categories: [ 'Science' ],
        averageRating: 4,
        ratingsCount: 1,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'iNKw0XuaSxoC',
        link: 'http://books.google.com/books/about/The_Technology_of_Orgasm.html?hl=&id=iNKw0XuaSxoC',
        thumbnail: 'http://books.google.com/books/content?id=iNKw0XuaSxoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Science, Technology, and Society',
        subtitle: 'An Encyclopedia',
        authors: [ 'Sal P. Restivo' ],
        publisher: 'Oxford University Press on Demand',
        publishedDate: '2005',
        description: '\'Science, Technology, and Society\' offers approximately 150 articles written by major scholars and experts from academic and scientific institutions worldwide. The theme is the functions and effects of science and technology in society and culture.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 701,
        printType: 'BOOK',
        categories: [ 'Social Science' ],
        averageRating: 5,
        ratingsCount: 1,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'A8C3m8rRba4C',
        link: 'http://books.google.com/books/about/Science_Technology_and_Society.html?hl=&id=A8C3m8rRba4C',
        thumbnail: 'http://books.google.com/books/content?id=A8C3m8rRba4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Children, Technology, and Culture',
        subtitle: 'The Impacts of Technologies in Children\'s Everyday Lives',
        authors:
         [ 'Phil Mizen',
           'Ian Hutchby',
           'Christopher John Pole',
           'Jo Moran-Ellis',
           'Angela Bolton' ],
        publisher: 'Psychology Press',
        publishedDate: '2001',
        description: 'Childhood is increasingly saturated by technology: from television to the Internet, video games to \'video nasties\', camcorders to personal computers. Children, Technology and Culture looks at the interplay of children and technology which poses critical questions for how we understand the nature of childhood in late modern society. This collection brings together researchers from a range of disciplines to address the following four aspects of this relationship between children and technology: *children\'s access to technologies and the implications for social relationships *the structural contexts of children\'s engagement with technologies with a focus on gender and the family *the situatedness of children\'s interactions with technological objects *the constitution of children and childhood through the mediations of technology _ This book represents a substantial contribution to contemporary social scientific thinking both about the nature of children and childhood, the social impacts of technologies and the various relationships between the two.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 189,
        printType: 'BOOK',
        categories: [ 'Education' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'NOfSHdweFLsC',
        link: 'http://books.google.com/books/about/Children_Technology_and_Culture.html?hl=&id=NOfSHdweFLsC',
        thumbnail: 'http://books.google.com/books/content?id=NOfSHdweFLsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Handbook of Display Technology',
        authors: [ 'Joseph A. Castellano' ],
        publisher: 'Gulf Professional Publishing',
        publishedDate: '1992',
        description: 'This book presents a comprehensive review of technical and commercial aspects of display technology. It provides design engineers with the information needed to select proper technology for new products. The book focuses on flat, thin displays such as light-emitting diodes, plasma display panels, and liquid crystal displays, but it also includes material on cathode ray tubes. Displays include a large number of products from televisions, auto dashboards, radios, and household appliances, to gasoline pumps, heart monitors, microwave ovens, and more. For more information on display technology, go to the experts: http://www.insightmedia.info/',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 341,
        printType: 'BOOK',
        categories: [ 'Computers' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'p68XfA0MHpoC',
        link: 'http://books.google.com/books/about/Handbook_of_Display_Technology.html?hl=&id=p68XfA0MHpoC',
        thumbnail: 'http://books.google.com/books/content?id=p68XfA0MHpoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Open Innovation',
        subtitle: 'The New Imperative for Creating and Profiting from Technology',
        authors: [ 'Henry William Chesbrough' ],
        publisher: 'Harvard Business Press',
        publishedDate: '2006',
        description: 'The information revolution has made for a radically more fluid knowledge environment, and the growth of venture capital has created inexorable pressure towards fast commercialisation of existing technologies Companies that don\'t use the technologies they develop are likely to lose them. Key features Over the past several years, Hank Chesbrough has done excellent research and writing on the commercialisation of technology and the changing role and context for R&D. This book represents a powerful synthesis of that work in the form of a new paradigm for managing corporate research and bringing new technologies to market Chesbrough impressively articulates his ideas and how they connect to each other, weaving several disparate areas of work R&D, corporate venturing, spinoffs, licensing and intellectual property into a single coherent framework',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 227,
        printType: 'BOOK',
        categories: [ 'Business & Economics' ],
        averageRating: 4,
        ratingsCount: 11,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'OeLIH89YiMcC',
        link: 'http://books.google.com/books/about/Open_Innovation.html?hl=&id=OeLIH89YiMcC',
        thumbnail: 'http://books.google.com/books/content?id=OeLIH89YiMcC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
    { title: 'Why Social Justice Matters',
        authors: [ 'Brian Barry' ],
        publisher: 'Polity',
        publishedDate: '2005-03-04',
        description: 'While social injustice has been increasing, the idea of social justice has been undermined by unfounded appeals to "personal responsibility" and "equal opportunity." Brian Barry exposes the shoddy logic and distortion of reality that underpins this ideology. Once we understand the role of the social structure in limiting options, we have to recognize that really putting into practice ideas such as equal opportunity and personal responsibility would require a fundamental transformation of almost all existing institutions. Barry argues that only if inequalities of wealth and income are kept within a narrow range can equal prospects for education, health and autonomy be realized. He proposes a number of policies to achieve a more equal society and argues that they are economically feasible. But are they politically possible? The apparent stability of the status quo is delusory, he responds: radical changes in our way of life are unavoidable.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 323,
        printType: 'BOOK',
        categories: [ 'Law' ],
        averageRating: 5,
        ratingsCount: 3,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'wwhOE1tDCOUC',
        link: 'http://books.google.com/books/about/Why_Social_Justice_Matters.html?hl=&id=wwhOE1tDCOUC',
        thumbnail: 'http://books.google.com/books/content?id=wwhOE1tDCOUC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Pedagogy of the Oppressed',
        subtitle: '30th Anniversary Edition',
        authors: [ 'Paulo Freire' ],
        publisher: 'Bloomsbury Publishing USA',
        publishedDate: '2014-08-18',
        description: 'First published in Portuguese in 1968, Pedagogy of the Oppressed was translated and published in English in 1970. The methodology of the late Paulo Freire has helped to empower countless impoverished and illiterate people throughout the world. Freire\'s work has taken on especial urgency in the United States and Western Europe, where the creation of a permanent underclass among the underprivileged and minorities in cities and urban centers is increasingly accepted as the norm. With a substantive new introduction on Freire\'s life and the remarkable impact of this book by writer and Freire confidant and authority Donaldo Macedo, this anniversary edition of Pedagogy of the Oppressed will inspire a new generation of educators, students, and general readers for years to come.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 192,
        printType: 'BOOK',
        categories: [ 'Education' ],
        averageRating: 5,
        ratingsCount: 1,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'oKQMBAAAQBAJ',
        link: 'https://market.android.com/details?id=book-oKQMBAAAQBAJ',
        thumbnail: 'http://books.google.com/books/content?id=oKQMBAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Social Justice Handbook',
        subtitle: 'Small Steps for a Better World',
        authors: [ 'Mae Elise Cannon' ],
        publisher: 'InterVarsity Press',
        publishedDate: '2009-09-11',
        description: '"Every day we are confronted by challenging societal problems, from poverty and institutional racism to AIDS and homelessness. It can all seem so overwhelming. But while none of us can do everything, all of us call do something. This handbook will help you discover what you can do." "Mae Elise Cannon provides a comprehensive resource for Christians committed to social justice. She presents biblical rationale for justice and explains a variety of Christian approaches to doing justice. Tracing the history of Christians in social engagement, she lifts out role models and examples from the Great Awakenings to the civil rights movement. A wide-ranging catalog of topics gives background information about justice issues at home and abroad." "The handbook includes dozens of practical exercises for taking action, highlighting how Christians and churches can make a difference. Also included are spiritual practices and resources to help us move from immobility to advocacy." "God has always worked through his peopleto accomplish improbable tasks. This handbook is an essential companion for living justly, loving mercy and walking humbly with your God."--BOOK JACKET.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 302,
        printType: 'BOOK',
        categories: [ 'Religion' ],
        averageRating: 2.5,
        ratingsCount: 2,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'qBD0ivtLwAkC',
        link: 'http://books.google.com/books/about/Social_Justice_Handbook.html?hl=&id=qBD0ivtLwAkC',
        thumbnail: 'http://books.google.com/books/content?id=qBD0ivtLwAkC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Morality and Social Justice',
        subtitle: 'Point/counterpoint',
        authors: [ 'James P. Sterba' ],
        publisher: 'Rowman & Littlefield',
        publishedDate: '1995',
        description: 'These original essays by seven leading contemporary political philosophers spanning the political spectrum explore the possibility of achieving agreement in political theory. Each philosopher defends in a principal essay his or her own view of social justice and also comments on two or more of the other essays. The result is a lively exchange that leaves the reader to judge to what degree the contributors achieve agreement or reconciliation.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 308,
        printType: 'BOOK',
        categories: [ 'Philosophy' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'vDxL3RJuWacC',
        link: 'http://books.google.com/books/about/Morality_and_Social_Justice.html?hl=&id=vDxL3RJuWacC',
        thumbnail: 'http://books.google.com/books/content?id=vDxL3RJuWacC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Men We Reaped',
        subtitle: 'A Memoir',
        authors: [ 'Jesmyn Ward' ],
        publisher: 'Bloomsbury Publishing USA',
        publishedDate: '2013-09-17',
        description: 'In this stirring and clear-eyed memoir, the 2011 National Book Award winner contends with the deaths of five young men dear to her, and the still great risk of being a black man in the rural South. "We saw the lightning and that was the guns; and then we heard the thunder and that was the big guns; and then we heard the rain falling and that was the blood falling; and when we came to get in the crops, it was dead men that we reaped.†? -Harriet Tubman In five years, Jesmyn Ward lost five young men in her life-to drugs, accidents, suicide, and the bad luck that can follow people who live in poverty, particularly black men. Dealing with these losses, one after another, made Jesmyn ask the question: Why? And as she began to write about the experience of living through all the dying, she realized the truth-and it took her breath away. Her brother and her friends all died because of who they were and where they were from, because they lived with a history of racism and economic struggle that fostered drug addiction and the dissolution of family and relationships. Jesmyn says the answer was so obvious she felt stupid for not seeing it. But it nagged at her until she knew she had to write about her community, to write their stories and her own. Jesmyn grew up in poverty in rural Mississippi. She writes powerfully about the pressures this brings, on the men who can do no right and the women who stand in for family in a society where the men are often absent. She bravely tells her story, revisiting the agonizing losses of her only brother and her friends. As the sole member of her family to leave home and pursue higher education, she writes about this parallel American universe with the objectivity distance provides and the intimacy of utter familiarity. A brutal world rendered beautifully, Jesmyn Ward\'s memoir will sit comfortably alongside Edwidge Danticat\'s Brother, I\'m Dying, Tobias Wolff\'s This Boy\'s Life, and Maya Angelou\'s I Know Why the Caged Bird Sings.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 272,
        printType: 'BOOK',
        categories: [ 'Biography & Autobiography' ],
        averageRating: 4,
        ratingsCount: 14,
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'x-_2fjm-RJEC',
        link: 'https://market.android.com/details?id=book-x-_2fjm-RJEC',
        thumbnail: 'http://books.google.com/books/content?id=x-_2fjm-RJEC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Social Justice Counseling',
        subtitle: 'The Next Steps Beyond Multiculturalism',
        authors: [ 'Rita Chi-Ying Chung', 'Frederic P. Bemak' ],
        publisher: 'SAGE',
        publishedDate: '2012',
        description: 'Social Justice Counseling develops a new frontier in multicultural social justice work and is the next step toward alleviating the injustices faced by individuals in society. Addressing issues of social class, race and ethnicity, and more, this book reflects the shift in recent years towards social justice counseling for all mental health professionals. It offers new and unique perspectives supplementing important social justice issues and enhancing the content taught in multicultural courses. The authors are leading authorities on multicultural and social justice counseling and have led the way to create a specialization with a nationally recognized program in multicultural social justice counseling.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 278,
        printType: 'BOOK',
        categories: [ 'Psychology' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'ZNvNWfwULOwC',
        link: 'http://books.google.com/books/about/Social_Justice_Counseling.html?hl=&id=ZNvNWfwULOwC',
        thumbnail: 'http://books.google.com/books/content?id=ZNvNWfwULOwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Principles of Social Justice',
        authors: [ 'David Miller' ],
        publisher: 'Harvard University Press',
        publishedDate: '1999',
        description: 'The meaning of social justice remains obscure, and existing theories put forward by political philosophers to explain it have failed to capture the way people think about issues of social justice. This text develops a new theory.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 337,
        printType: 'BOOK',
        categories: [ 'Philosophy' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'y2wMzJtEZ_8C',
        link: 'http://books.google.com/books/about/Principles_of_Social_Justice.html?hl=&id=y2wMzJtEZ_8C',
        thumbnail: 'http://books.google.com/books/content?id=y2wMzJtEZ_8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Social Justice and the City',
        authors: [ 'David Harvey' ],
        publisher: 'University of Georgia Press',
        publishedDate: '2010-04-15',
        description: 'Throughout his distinguished and influential career, David Harvey has defined and redefined the relationship between politics, capitalism, and the social aspects of geographical theory. Laying out Harvey\'s position that geography could not remain objective in the face of urban poverty and associated ills, Social Justice and the City is perhaps the most widely cited work in the field. Harvey analyzes core issues in city planning and policy--employment and housing location, zoning, transport costs, concentrations of poverty--asking in each case about the relationship between social justice and space. How, for example, do built-in assumptions about planning reinforce existing distributions of income? Rather than leading him to liberal, technocratic solutions, Harvey\'s line of inquiry pushes him in the direction of a "revolutionary geography," one that transcends the structural limitations of existing approaches to space. Harvey\'s emphasis on rigorous thought and theoretical innovation gives the volume an enduring appeal. This is a book that raises big questions, and for that reason geographers and other social scientists regularly return to it.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 356,
        printType: 'BOOK',
        categories: [ 'Social Science' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'VCwLi2nVmooC',
        link: 'https://market.android.com/details?id=book-VCwLi2nVmooC',
        thumbnail: 'http://books.google.com/books/content?id=VCwLi2nVmooC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'A History of Social Justice and Political Power in the Middle East',
        subtitle: 'The Circle of Justice from Mesopotamia to Globalization',
        authors: [ 'Linda T. Darling' ],
        publisher: 'Routledge',
        publishedDate: '2013',
        description: 'From ancient Mesopotamia into the 20thcentury, "the Circle of Justice" as a concept has pervaded Middle Eastern political thought and underpinned the exercise of power in the Middle East. The Circle of Justice depicts graphically how a government’s justice toward the population generates political power, military strength, prosperity, and good administration. This book traces this set of relationships from its earliest appearance in the political writings of the Sumerians through four millennia of Middle Eastern culture. It explores how people conceptualized and acted upon this powerful insight, how they portrayed it in symbol, painting, and story, and how they transmitted it from one regime to the next. Moving towards the modern day, the author shows how, although the Circle of Justice was largely dropped from political discourse, it did not disappear from people’s political culture and expectations of government. The book demonstrates the Circle’s relevance to the Iranian Revolution and the rise of Islamist movements all over the Middle East, and suggests how the concept remains relevant in an age of capitalism. A "must read" for students, policymakers, and ordinary citizens, this book will be an important contribution to the areas of political history, political theory, Middle East studies and Orientalism.',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 399,
        printType: 'BOOK',
        categories: [ 'History' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'u2sxtycuGvoC',
        link: 'http://books.google.com/books/about/A_History_of_Social_Justice_and_Politica.html?hl=&id=u2sxtycuGvoC',
        thumbnail: 'http://books.google.com/books/content?id=u2sxtycuGvoC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} },
      { title: 'Social Justice',
        subtitle: 'Politics, Technology, and Culture for a Better World',
        authors: [ 'Susan Magarey' ],
        publisher: 'Wakefield Press',
        publishedDate: '1998-01-01',
        description: 'Egg-heads in an ivory tower? Dreary boffins carrying out useless research at the tax-payer\'s expense? Computer-nerds? Do such figures make you think of people working in humanities and social sciences in universities? This book shows just how wrong such representations are',
        industryIdentifiers: [ [Object], [Object] ],
        pageCount: 90,
        printType: 'BOOK',
        categories: [ 'Culture' ],
        maturityRating: 'NOT_MATURE',
        language: 'en',
        id: 'MK-sWQWaI74C',
        link: 'http://books.google.com/books/about/Social_Justice.html?hl=&id=MK-sWQWaI74C',
        thumbnail: 'http://books.google.com/books/content?id=MK-sWQWaI74C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
        images: {} } ]

module.exports = { book_data }